config/routes.rb
Rails.application.routes.draw do
 resources :countries, :cities
 root to: 'countries#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    City.create(whitelister)
    redirect_to(cities_path)
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    city = City.find(params[:id])
    city.update(whitelister)
    redirect_to(cities_path)
  end

  def show
    @city = City.find(params[:id])
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to(cities_path)
  end

private
def whitelister
  params.require(:city).permit(:name, :population, :photo, :country_id)
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
  end 

  def new
    @country = Country.new
  end

  def create
    # render text: params.inspect
    Country.create(whitelister)
    redirect_to(countries_path)
  end

  def show
    @country = Country.find(params[:id])
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to(countries_path)
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    country = Country.find(params[:id])
    country.update(whitelister)
    redirect_to(countries_path)
  end

  private 
  def whitelister
    params.require(:country).permit(:name, :flag, :population, :size, :language, :currency, :exchange_rate)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :population %>
  <%= f.text_field :population %>
  <br>
  <%= f.label :country_id %>
  <%= f.collection_select :country_id, Country.order(:name),:id,:name, include_blank: false %>
  <br>
  <%= f.label :photo %>
  <%= f.text_field :photo %>
  <br>
  <%= f.submit button_text %>
  <% end %>

app/views/cities/edit.html.erb
<%= render partial: 'form', object: @city, locals: { button_text: "Update" } %>

app/views/cities/index.html.erb
<table>
  <tr> 
    <th>Name</th>
    <th>Country</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  
<% @cities.each do |city| %>
  <tr>
    <td><%= link_to(city.name, city_path(city)) %></td>
    <td><%= city.country.name %></td>
    <td><%= link_to('Edit', edit_city_path(city)) %></td>
    <td><%= link_to('Delete', city_path(city), method: :delete) %></td>
  </tr>
<% end %>

</table>

app/views/cities/new.html.erb
<%= render partial: 'form', object: @city, locals: { button_text: "Create" } %>

app/views/cities/show.html.erb
<h1>Name: <%= @city.name %></h1>

<strong>Population: </strong><%= @city.population %>

<strong>Country: </strong> <%= link_to(@city.country.name, country_path(@city.country)) %>
<br><%= image_tag(@city.photo) if @city.photo %>

app/views/countries/_countriestable.html.erb
<table>
<tr>
<th>Name</th>
<th>Flag</th>
<th>Size</th>
<th>Language</th>
<th>Population</th>
<th>Show</th>
<th>Edit</th>
<th>Delete</th>
</tr>

<% @countries.each do |country| %>
<tr>
<td><%= country.name %></td>
<td><%= image_tag(country.flag, alt: "Flag of #{country.name}", width: 100) %></td>
<td><%= country.size %></td>
<td><%= country.language %></td>
<td><%= country.population %></td>
<td><%= link_to('Show', country_path(country), {:class=>"button"}) %></td>
<td><%= link_to('Edit', edit_country_path(country), {:class=>"button"}) %></td>
<td><%= link_to('Delete', country_path(country), { :class=>"button", :method=>:delete},) %></td>
</tr>
<% end %>
</table>

app/views/countries/_countrydetails.html.erb
<h2><%= @country.name %></h2>
<%= image_tag(@country.flag, width: 250) %>
<ul>
  <li>Name: <%= @country.name %></li>
  <li>Size: <%= number_to_human(@country.size) %> KM</li>
  <li>Population: <%= number_to_human(@country.population) %></li>
  <li>Language: <%= @country.language %></li>
</ul>

app/views/countries/_form.html.erb
<%= form_for @country do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :flag %>
  <%= f.text_field :flag %>
  <br>
  <%= f.label :size %>
  <%= f.text_field :size %>
  <br>
  <%= f.label :language %>
  <%= f.text_field :language %>
  <br>
  <%= f.label :population %>
  <%= f.text_field :population %>
  <br>
  <%= f.label :currency, 'Currency Symbol' %>
  <%= f.text_field :currency %>
  <br>
  <%= f.label :exchange_rate %>
  <%= f.text_field :exchange_rate %>
  <br>
  <%= f.submit 'Submit!' %>
<% end %>

app/views/countries/_listcities.html.erb
<h2>Cities</h2>


<% @country.cities.each do |city| %>
<%= link_to(city.name, city_path(city)) %>
<% end %>

app/views/countries/edit.html.erb
<%= render partial: 'form' %>

app/views/countries/index.html.erb
<div>
<%= render partial: 'countries/countriestable' %>
</div>

app/views/countries/new.html.erb
<%= render partial: 'form' %>

app/views/countries/show.html.erb
<%= render partial: 'countrydetails', object: @country %>

<h2>Convert Currency</h2>
<%= form_tag(country_path, method: :get) do %>
  <p>Enter amount in Sterling:
  <%= text_field_tag :inputnumber %>
  <%= submit_tag "go" %>
<% end %>
<% calculation = params['inputnumber']*@country.exchange_rate if params['inputnumber']%>
<%= "That'll be #{@country.currency}#{(@country.exchange_rate*params['inputnumber'].to_f).round(2)}" if params['inputnumber'] %>


<%= render partial: 'listcities', object: @country %>

app/views/layouts/_header.html.erb
<div id="header-wrapper">
<div id="logo"><h1>CIA mega secret app</h1></div>
<h2>Our unhackable resource where we keep tabs on the world!</h2>
<h3>Hosted ENTIRELY on TalkTalk</h3>
</div>

app/views/layouts/_menu.html.erb
<div id="menu">
<br><%= link_to('Countries list', countries_path) %>
<%= link_to('New Country', new_country_path) %>
<br>
<%= link_to('Cities List', cities_path) %>
<%= link_to('New City', new_city_path) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CiaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header' %>
<%= render partial:'layouts/menu' %>
<div id="page-wrapper">
<%= yield %>
</div>
<div id="copyright"><p>Since this is totally secure in every way, don't tell your friends!</p></div>
</body>
</html>